# Uncomment the next line to define a global platform for your project

source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target 'RongCloudDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RongCloudDemo
  pod 'RongCloudIM/IMKit', '~> 5.3.1' # 即时通讯基础 UI 组件

  pod 'SnapKit'
  pod 'NotificationToast'
  pod 'Alamofire'

  # Debug
  pod 'DoraemonKit/Core', '~> 3.0.4', :configurations => ['Debug']  #必选
#  pod 'DoraemonKit/WithLogger', '~> 3.0.4', :configurations => ['Debug'] #可选
#  pod 'DoraemonKit/WithGPS', '~> 3.0.4', :configurations => ['Debug'] #可选
#  pod 'DoraemonKit/WithLoad', '~> 3.0.4', :configurations => ['Debug'] #可选
#  pod 'DoraemonKit/WithWeex', '~> 3.0.4', :configurations => ['Debug'] #可选
#  pod 'DoraemonKit/WithDatabase', '~> 3.0.4', :configurations => ['Debug'] #可选
#  pod 'DoraemonKit/WithMLeaksFinder', '3.0.4', :configurations => ['Debug'] #可选
  
end
