# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'AppCenter' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AppCenter 
  pod 'SnapKit', '~> 5.6.0'
  
  pod 'LookinServer', :configurations => ['Debug']

  target 'AppCenterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppCenterUITests' do
    # Pods for testing
  end

end
